env                       = "test"
location                  = "uksouth"
subscription_id           = "<test-subscription-id>"
product                   = "mhpd"
hub_firewall_private_ip   = ""
http_correlation_protocol = "W3C"
verbosity                 = "verbose"
