env                       = "prod"
location                  = "ukwest"
subscription_id           = "<prod-subscription-id>"
product                   = "mhpd"
hub_firewall_private_ip   = "<prod-hub-firewall-private-ip>"
http_correlation_protocol = "W3C"
verbosity                 = "verbose"
