env                       = "nft"
location                  = "uksouth"
subscription_id           = "7fc6934b-d819-44b2-90be-c34c87b2854b"
product                   = "mhpd"
hub_firewall_private_ip   = "10.0.0.4"
http_correlation_protocol = "W3C"
verbosity                 = "verbose"
