env                       = "stg"
location                  = "ukwest"
subscription_id           = "<stg-subscription-id>"
product                   = "mhpd"
hub_firewall_private_ip   = "<stg-hub-firewall-private-ip>"
http_correlation_protocol = "W3C"
verbosity                 = "verbose"
